import { useCallback } from "react";
import { ConversationMessage, Speaker, SessionInsights, LANGUAGES } from "@/lib/constants";

export interface TranscriptData {
  sessionId: string;
  timestamp: number;
  duration: number;
  speakers: Speaker[];
  messages: ConversationMessage[];
  insights: SessionInsights;
}

/**
 * Hook for generating and downloading formatted transcripts
 */
export function useTranscriptDownload() {
  
  /**
   * Format duration in seconds to readable string
   */
  const formatDuration = useCallback((seconds: number): string => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = Math.floor(seconds % 60);
    
    if (hours > 0) {
      return `${hours}h ${minutes}m ${secs}s`;
    }
    return `${minutes}m ${secs}s`;
  }, []);

  /**
   * Format timestamp to readable time
   */
  const formatTime = useCallback((timestamp: number): string => {
    return new Date(timestamp).toLocaleTimeString([], { 
      hour: '2-digit', 
      minute: '2-digit', 
      second: '2-digit' 
    });
  }, []);

  /**
   * Generate formatted transcript text
   */
  const generateTranscript = useCallback((data: TranscriptData): string => {
    const { sessionId, timestamp, duration, speakers, messages, insights } = data;
    const sessionDate = new Date(timestamp);
    
    let transcript = '';
    
    // Header
    transcript += '\n';
    transcript += '                        NEURALECHO TRANSCRIPT                        \n';
    transcript += '\n\n';
    
    // Session metadata
    transcript += 'SESSION INFORMATION\n';
    transcript += '\n';
    transcript += `Session ID: ${sessionId}\n`;
    transcript += `Date: ${sessionDate.toLocaleDateString()}\n`;
    transcript += `Time: ${sessionDate.toLocaleTimeString()}\n`;
    transcript += `Duration: ${formatDuration(duration)}\n`;
    transcript += `Total Messages: ${messages.length}\n\n`;
    
    // Speakers
    transcript += 'PARTICIPANTS\n';
    transcript += '\n';
    speakers.forEach((speaker, index) => {
      const lang = LANGUAGES.find(l => l.code === speaker.language);
      const viewLang = LANGUAGES.find(l => l.code === speaker.viewLanguage);
      transcript += `${index + 1}. ${speaker.name}\n`;
      transcript += `   Speaking: ${lang?.label || speaker.language} (${lang?.region || ''})\n`;
      transcript += `   Reading: ${viewLang?.label || speaker.viewLanguage} (${viewLang?.region || ''})\n`;
    });
    transcript += '\n';
    
    // Performance insights
    transcript += 'SESSION INSIGHTS\n';
    transcript += '\n';
    transcript += `Average Translation Latency: ${insights.avgTranslationLatency.toFixed(0)}ms\n`;
    transcript += `Average Confidence: ${(insights.avgConfidence * 100).toFixed(1)}%\n`;
    transcript += `Error Rate: ${(insights.errorRate * 100).toFixed(1)}%\n`;
    transcript += `Network Delay: ${insights.avgNetworkDelay.toFixed(0)}ms\n\n`;
    
    // Conversation
    transcript += 'CONVERSATION TRANSCRIPT\n';
    transcript += '\n\n';
    
    if (messages.length === 0) {
      transcript += '[No messages recorded]\n\n';
    } else {
      messages.forEach((message, index) => {
        const speaker = speakers.find(s => s.id === message.speakerId);
        const sourceLang = LANGUAGES.find(l => l.code === message.sourceLang);
        const time = formatTime(message.timestamp);
        const latency = message.latency ? ` (${message.latency}ms)` : '';
        
        transcript += `[${time}] ${speaker?.name || `Speaker ${message.speakerId + 1}`}${latency}\n`;
        
        // Original text
        if (message.sourceText && message.sourceText.trim() !== "(no transcript)") {
          transcript += `${sourceLang?.label || message.sourceLang}: "${message.sourceText}"\n`;
          
          // Translations
          Object.entries(message.translations).forEach(([key, translation]) => {
            if (translation && translation.trim() !== "(no response)") {
              if (key === "ai-response") {
                // Determine target language
                const targetLangCode = message.sourceLang === "en-US" ? "fr-CA" : "en-US";
                const targetLang = LANGUAGES.find(l => l.code === targetLangCode);
                transcript += `${targetLang?.label || targetLangCode}: "${translation}"\n`;
              } else {
                transcript += `${key}: "${translation}"\n`;
              }
            }
          });
        } else {
          transcript += `[No speech detected]\n`;
        }
        
        transcript += '\n';
      });
    }
    
    // Footer
    transcript += '\n';
    transcript += `Generated by NeuralEcho on ${new Date().toLocaleString()}\n`;
    transcript += 'A GoML Demo Application - https://goml.io\n';
    transcript += '\n';
    
    return transcript;
  }, [formatDuration, formatTime]);

  /**
   * Download transcript as a .txt file
   */
  const downloadTranscript = useCallback((data: TranscriptData) => {
    const transcriptText = generateTranscript(data);
    const sessionDate = new Date(data.timestamp);
    const dateStr = sessionDate.toISOString().slice(0, 19).replace(/[:.]/g, '-');
    const durationStr = formatDuration(data.duration);
    
    const filename = `neuralecho-transcript-${dateStr}-${durationStr}-${data.sessionId}.txt`;
    
    const blob = new Blob([transcriptText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [generateTranscript, formatDuration]);

  /**
   * Generate transcript data from current app state
   */
  const createTranscriptData = useCallback((
    messages: ConversationMessage[],
    speakers: Speaker[],
    insights: SessionInsights,
    sessionStartTime: number
  ): TranscriptData => {
    const sessionId = `session-${sessionStartTime}-${Math.random().toString(36).slice(2, 6)}`;
    const duration = insights.sessionDuration;
    
    return {
      sessionId,
      timestamp: sessionStartTime,
      duration,
      speakers,
      messages,
      insights,
    };
  }, []);

  return {
    generateTranscript,
    downloadTranscript,
    createTranscriptData,
  };
}